
import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: "#f9f3ea",
    },
    scrollView: {
      flex: 1,
      padding: 20,
      marginBottom: 50,
    },
    title: {
      fontSize: 32,
      fontWeight: "bold",
      color: "#6b4226",
      marginBottom: 25,
      textAlign: "center",
      textShadowColor: "rgba(0, 0, 0, 0.1)",
      textShadowOffset: { width: 1, height: 1 },
      textShadowRadius: 2,
    },
    statsContainer: {
      backgroundColor: "#fff",
      padding: 20,
      borderRadius: 15,
      marginBottom: 25,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 5,
    },
    statText: {
      fontSize: 18,
      color: "#6b4226",
      marginBottom: 12,
      fontWeight: "500",
    },
    button: {
      backgroundColor: "#6b4226",
      padding: 16,
      borderRadius: 12,
      width: "100%",
      alignItems: "center",
      marginVertical: 12,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    buttonText: {
      color: "#fff",
      fontSize: 16,
      fontWeight: "bold",
      letterSpacing: 0.5,
    },
    calendarContainer: {
      backgroundColor: "#fff",
      borderRadius: 15,
      padding: 15,
      marginBottom: 20,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 5,
    },
    selectedDateContainer: {
      backgroundColor: "#fff",
      borderRadius: 15,
      padding: 20,
      marginBottom: 20,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 5,
    },
    selectedDateTitle: {
      fontSize: 20,
      fontWeight: "bold",
      color: "#6b4226",
      marginBottom: 15,
      textAlign: "center",
    },
    selectedDateOrders: {
      maxHeight: 400,
    },
    orderCard: {
      backgroundColor: "#fff",
      padding: 18,
      borderRadius: 12,
      marginBottom: 12,
      borderLeftWidth: 4,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 3,
      elevation: 2,
    },
    orderId: {
      fontSize: 16,
      fontWeight: "bold",
      color: "#6b4226",
      marginBottom: 4,
    },
    orderStatus: {
      fontSize: 14,
      fontWeight: "bold",
      marginVertical: 6,
      textTransform: "capitalize",
    },
    orderCustomer: {
      fontSize: 14,
      color: "#666",
      marginBottom: 4,
    },
    orderTotal: {
      fontSize: 16,
      fontWeight: "bold",
      color: "#6b4226",
      marginTop: 6,
    },
    noOrdersText: {
      textAlign: "center",
      color: "#666",
      fontSize: 16,
      fontStyle: "italic",
      marginTop: 20,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
    },
    errorText: {
      color: "#d9534f",
      textAlign: "center",
      marginTop: 10,
      fontSize: 14,
    },
    alertBox: {
      backgroundColor: "#fff3cd",
      borderLeftWidth: 5,
      borderLeftColor: "#ffcc00",
      padding: 15,
      borderRadius: 10,
      marginBottom: 20,
    },
    alertTitle: {
      fontSize: 18,
      fontWeight: "bold",
      color: "#856404",
      marginBottom: 6,
    },
    alertContent: {
      fontSize: 16,
      color: "#856404",
    },
    chartTitle: {
      fontSize: 20,
      fontWeight: "bold",
      color: "#6b4226",
      textAlign: "center",
      marginBottom: 10,
      marginTop: 20,
    },
  });

  export default styles;