import { StyleSheet, Platform } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f7efe5", // רקע חדשני ובהיר
    paddingHorizontal: 15,
  },
  titleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
    marginBottom: 10,
    gap: 8,
  },
  title: {
    fontSize: 26,
    fontWeight: "700",
    textAlign: "center",
    color: "#23232b", // כהה וקריא
    letterSpacing: 0.2,
    fontFamily: Platform.OS === "ios" ? "Avenir Next" : "Roboto",
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#fdf7f1", // בהיר, מעט נבדל מהרקע
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    shadowColor: "#bdbdbd",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
    marginBottom: 2,
  },
  headerCell: {
    flex: 1,
    color: "#23232b",
    fontWeight: "700",
    textAlign: "center",
    fontSize: 16,
    fontFamily: Platform.OS === "ios" ? "Avenir Next" : "Roboto",
    minWidth: 60,
    paddingHorizontal: 8,
    letterSpacing: 0.1,
  },
  headerCellText: {
    color: "#23232b",
    fontWeight: "700",
    fontSize: 15,
    textAlign: "center",
    letterSpacing: 0.1,
  },
  nameHeaderCell: {
    flex: 1.4,
    color: "#23232b",
    fontWeight: "700",
    textAlign: "center",
    fontSize: 15,
    minWidth: 100,
    paddingHorizontal: 8,
    letterSpacing: 0.1,
  },
  statusHeaderCell: {
    flex: 1,
    color: "#23232b",
    fontWeight: "700",
    textAlign: "center",
    fontSize: 15,
    minWidth: 80,
    paddingHorizontal: 8,
    letterSpacing: 0.1,
  },
  scrollViewContent: {
    paddingBottom: Platform.OS === 'ios' ? 20 : 40,
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 16,
    paddingHorizontal: 14,
    backgroundColor: "#fff",
    marginBottom: 14,
    borderRadius: 20,
    borderWidth: 0,
    // borderColor: "#e0dcd5",
    shadowColor: "#bdbdbd",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 4,
    gap: 10,
    marginHorizontal: 4,
  },

  orderCard: {
    backgroundColor: "#fff",
    borderRadius: 20,
    marginBottom: 18,
    padding: 18,
    shadowColor: "#bdbdbd",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 4,
    flexDirection: "column",
    gap: 10,
    position: "relative",
    borderBottomWidth: 1,
    borderBottomColor: "#f1e8d9",
    paddingHorizontal: 8,
    marginHorizontal: 4,
  },
  cell: {
    flex: 1,
    flexShrink: 1,
    textAlign: "center",
    color: "#23232b",
    minWidth: 80,
    fontSize: 15,
    fontWeight: "500",
    paddingHorizontal: 6,
    flexWrap: "nowrap",
    overflow: "hidden",
    fontFamily: Platform.OS === "ios" ? "Avenir Next" : "Roboto",
    letterSpacing: 0.05,
  },
  pending: { color: "#ff9800", fontWeight: "700" },
  confirmed: { color: "#1976d2", fontWeight: "700" },
  delivered: { color: "#43a047", fontWeight: "700" },
  cancelled: { color: "#e53935", fontWeight: "700" },
  menuButton: {
    paddingHorizontal: 10,
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    top: 14,
    right: 14,
    zIndex: 10,
    backgroundColor: "transparent",
  },
  menuText: {
    fontSize: 24,
    color: "#6b4226",
    textAlign: "center",
    width: 20,
    height: 20,
    includeFontPadding: false,
    textAlignVertical: "center",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: "#fff",
    padding: 28,
    borderRadius: 22,
    width: "85%",
    alignItems: "center",
    shadowColor: "#bdbdbd",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 14,
    elevation: 8,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#23232b",
    marginBottom: 14,
    fontFamily: Platform.OS === "ios" ? "Avenir Next" : "Roboto",
    letterSpacing: 0.2,
  },
  modalSubTitle: {
    fontSize: 16,
    color: "#68686f",
    marginBottom: 10,
    fontWeight: "500",
    fontFamily: Platform.OS === "ios" ? "Avenir Next" : "Roboto",
  },
  input: {
    width: "100%",
    height: 80,
    borderWidth: 1.5,
    borderColor: "#e0dcd5",
    borderRadius: 12,
    padding: 12,
    marginBottom: 14,
    backgroundColor: "#f9f7f2",
    textAlignVertical: "top",
    fontSize: 15,
    color: "#23232b",
    fontFamily: Platform.OS === "ios" ? "Avenir Next" : "Roboto",
  },
  sendButton: {
    backgroundColor: "#6b4226",
    paddingVertical: 14,
    paddingHorizontal: 25,
    borderRadius: 20,
    alignItems: "center",
    width: "100%",
    shadowColor: "#bdbdbd",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.17,
    shadowRadius: 10,
    elevation: 4,
    marginBottom: 6,
    marginTop: 4,
    // אפקט מעבר
  },
  sendButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 17,
    letterSpacing: 0.1,
    fontFamily: Platform.OS === "ios" ? "Avenir Next" : "Roboto",
  },
  closeButton: {
    backgroundColor: "#e53935",
    paddingVertical: 12,
    paddingHorizontal: 25,
    borderRadius: 20,
    alignItems: "center",
    width: "100%",
    marginTop: 10,
    shadowColor: "#bdbdbd",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.17,
    shadowRadius: 10,
    elevation: 4,
  },
  closeButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 17,
    fontFamily: Platform.OS === "ios" ? "Avenir Next" : "Roboto",
  },
  filterGroupWrapper: {
    backgroundColor: "#f7efe5",
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginHorizontal: 0,
    marginBottom: 20,
    marginTop: 0,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#bdbdbd",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  filterContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
    marginBottom: 10,
    width: "100%",
  },
  filterButton: {
    paddingVertical: 10,
    paddingHorizontal: 18,
    backgroundColor: "#e8e1d8",
    borderRadius: 12,
    minWidth: 120,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#bdbdbd",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.10,
    shadowRadius: 6,
    elevation: 2,
    height: 42,
  },
  activeFilter: {
    backgroundColor: "#6b4226",
    shadowColor: "#6b4226",
    shadowOpacity: 0.18,
    elevation: 4,
  },
  filterButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 15,
    letterSpacing: 0.1,
    fontFamily: Platform.OS === "ios" ? "Avenir Next" : "Roboto",
  },
  modalButton: {
    paddingVertical: 14,
    backgroundColor: "#f7efe5",
    marginVertical: 7,
    width: "100%",
    alignItems: "center",
    borderRadius: 18,
    shadowColor: "#bdbdbd",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.10,
    shadowRadius: 6,
    elevation: 2,
  },
  selectedStatus: {
    backgroundColor: "#ffe3b2",
  },
  modalButtonClose: {
    paddingVertical: 14,
    backgroundColor: "#e53935",
    marginVertical: 7,
    width: "100%",
    alignItems: "center",
    borderRadius: 18,
    shadowColor: "#bdbdbd",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.10,
    shadowRadius: 6,
    elevation: 2,
  },
  modalButtonConfirm: {
    paddingVertical: 14,
    backgroundColor: "#32CD32",
    marginTop: 14,
    width: "100%",
    alignItems: "center",
    borderRadius: 18,
    shadowColor: "#bdbdbd",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.10,
    shadowRadius: 6,
    elevation: 2,
  },
  searchContainer: {
    width: "100%",
    backgroundColor: "#f3e8dc",
    borderRadius: 16,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 2,
    marginTop: 6,
    marginBottom: 0,
    shadowColor: "#bdbdbd",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 1,
  },
  searchInput: {
    flex: 1,
    borderWidth: 0,
    borderColor: "transparent",
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 8,
    backgroundColor: "transparent",
    color: "#23232b",
    fontSize: 16,
    fontFamily: Platform.OS === "ios" ? "Avenir Next" : "Roboto",
    textAlign: "left",
  },
  priorityHeaderCell: {
    width: 34,
    color: "#23232b",
    fontWeight: "700",
    textAlign: "center",
    paddingHorizontal: 8,
    fontFamily: Platform.OS === "ios" ? "Avenir Next" : "Roboto",
  },
  priorityButton: {
    width: 34,
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    top: 10,
    right: 10,
    zIndex: 2,
  },
  priorityRow: {
    backgroundColor: "#fffbe8",
    borderLeftWidth: 5,
    borderLeftColor: "#FFD700",
  },
  statusDropdown: {
    position: 'absolute',
    top: 120,
    right: 15,
    backgroundColor: '#fff',
    borderRadius: 14,
    padding: 10,
    shadowColor: '#bdbdbd',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.14,
    shadowRadius: 8,
    elevation: 6,
    zIndex: 1000,
  },
  statusDropdownItem: {
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#f1e8d9',
  },
  statusDropdownText: {
    color: '#23232b',
    fontSize: 15,
    fontWeight: "500",
    fontFamily: Platform.OS === "ios" ? "Avenir Next" : "Roboto",
  },
  noResultsText: {
    textAlign: "center",
    color: "#bdbdbd",
    fontSize: 17,
    marginTop: 24,
    fontStyle: "italic",
    marginHorizontal: 20,
    fontFamily: Platform.OS === "ios" ? "Avenir Next" : "Roboto",
  },
  orderIdText: {
    fontSize: 14,
    color: "#555",
    marginBottom: 4,
    fontWeight: "500",
  },
});

export default styles;