import { StyleSheet, Platform } from 'react-native';

const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: "#f9f3ea",
      paddingTop: Platform.OS === 'ios' ? 20 : 40,
      paddingHorizontal: 15,
    },
    title: {
      fontSize: 24,
      fontWeight: "bold",
      textAlign: "center",
      marginBottom: 15,
      color: "#6b4226",
    },
    tableHeader: {
      flexDirection: "row",
      backgroundColor: "#6b4226",
      paddingVertical: 12,
      paddingHorizontal: 8,
      borderRadius: 5,
      alignItems: "center",
    },
    headerCell: {
      flex: 1,
      color: "#fff",
      fontWeight: "bold",
      textAlign: "center",
      fontSize: 13,
      minWidth: 50,
      paddingHorizontal: 8,
    },
    headerCellText: {
      color: "#fff",
      fontWeight: "bold",
      fontSize: 13,
      textAlign: "center",
    },
    nameHeaderCell: {
      flex: 1.2,
      color: "#fff",
      fontWeight: "bold",
      textAlign: "center",
      fontSize: 13,
      minWidth: 90,
      paddingHorizontal: 8,
    },
    statusHeaderCell: {
      flex: 0.8,
      color: "#fff",
      fontWeight: "bold",
      textAlign: "center",
      fontSize: 13,
      minWidth: 70,
      paddingHorizontal: 8,
    },
    scrollViewContent: {
      paddingBottom: Platform.OS === 'ios' ? 20 : 40,
    },
    row: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingVertical: 15,
      paddingHorizontal: 8,
      backgroundColor: "#fff",
      marginVertical: 5,
      borderRadius: 5,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.2,
      elevation: 2,
      gap: 8,
    },
    cell: {
      flex: 1,
      textAlign: "center",
      color: "#6b4226",
      minWidth: 50,
      fontSize: 13,
      paddingHorizontal: 8,
      alignItems: "center",
      flexDirection: "column",
    },
    pending: { color: "#FFA500", fontWeight: "bold" },
    confirmed: { color: "#007bff", fontWeight: "bold" },
    delivered: { color: "#28a745", fontWeight: "bold" },
    cancelled: { color: "#d9534f", fontWeight: "bold" },
    menuButton: {
      paddingHorizontal: 10,
      alignItems: "center",
      justifyContent: "center",
    },
    menuText: { fontSize: 24, fontWeight: "bold", textAlign: "center" },
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.5)",
      justifyContent: "center",
      alignItems: "center",
    },
    modalContent: {
      backgroundColor: "#f9f3ea",
      padding: 20,
      borderRadius: 10,
      width: "80%",
      alignItems: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 3,
      elevation: 3,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: "bold",
      color: "#6b4226",
      marginBottom: 10,
    },
    modalSubTitle: { fontSize: 16, color: "#6b4226", marginBottom: 10 },
    input: {
      width: "100%",
      height: 80,
      borderWidth: 1,
      borderColor: "#ccc",
      borderRadius: 8,
      padding: 10,
      marginBottom: 10,
      backgroundColor: "#f9f9f9",
      textAlignVertical: "top",
    },
    sendButton: {
      backgroundColor: "#6b4226",
      paddingVertical: 12,
      paddingHorizontal: 25,
      borderRadius: 8,
      alignItems: "center",
      width: "100%",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 3,
      elevation: 3,
    },
    sendButtonText: { color: "#fff", fontWeight: "bold", fontSize: 16 },
    closeButton: {
      backgroundColor: "#d9534f",
      paddingVertical: 10,
      paddingHorizontal: 25,
      borderRadius: 8,
      alignItems: "center",
      width: "100%",
      marginTop: 10,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 3,
      elevation: 3,
    },
    closeButtonText: { color: "#fff", fontWeight: "bold", fontSize: 16 },
    filterContainer: {
      flexDirection: "row",
      paddingVertical: 10,
      paddingHorizontal: 5,
    },
    filterButton: {
      padding: 10,
      backgroundColor: "#ddd",
      borderRadius: 5,
      marginHorizontal: 5,
      minWidth: 100,
    },
    activeFilter: { backgroundColor: "#6b4226" },
    filterButtonText: { color: "#fff", fontWeight: "bold" },
    modalButton: {
      padding: 10,
      backgroundColor: "#fff",
      marginVertical: 5,
      width: "100%",
      alignItems: "center",
      borderRadius: 8,
    },
    selectedStatus: { backgroundColor: "#D2B48C" },
    modalButtonClose: {
      padding: 10,
      backgroundColor: "#d9534f",
      marginVertical: 5,
      width: "100%",
      alignItems: "center",
      borderRadius: 8,
    },
    modalButtonConfirm: {
      padding: 12,
      backgroundColor: "#32CD32",
      marginTop: 10,
      width: "100%",
      alignItems: "center",
      borderRadius: 8,
    },
    searchContainer: {
      marginBottom: 10,
    },
    searchInput: {
      borderWidth: 1,
      borderColor: "#ccc",
      borderRadius: 8,
      padding: 10,
      backgroundColor: "#fff",
      textAlign: "right",
      marginBottom: 10,
    },
    priorityHeaderCell: {
      width: 34,
      color: "#fff",
      fontWeight: "bold",
      textAlign: "center",
      paddingHorizontal: 8,
    },
    priorityButton: {
      width: 34,
      justifyContent: "center",
      alignItems: "center",
    },
    priorityRow: {
      backgroundColor: "#fff9e6",
      borderLeftWidth: 4,
      borderLeftColor: "#FFD700",
    },
    statusDropdown: {
      position: 'absolute',
      top: 120,
      right: 15,
      backgroundColor: '#fff',
      borderRadius: 8,
      padding: 8,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
      zIndex: 1000,
    },
    statusDropdownItem: {
      paddingVertical: 10,
      paddingHorizontal: 15,
      borderBottomWidth: 1,
      borderBottomColor: '#eee',
    },
    statusDropdownText: {
      color: '#6b4226',
      fontSize: 14,
    },
  });

  
  export default styles;