import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: { flex: 1, padding: 15, backgroundColor: "#f9f3ea" },
    selectButton: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: "#d6b48f",
      justifyContent: "center",
      alignItems: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 4,
      marginRight: 10,
    },
  
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    addButton: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: "#e4c8a0",
      justifyContent: "center",
      alignItems: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 4,
      marginRight: 10,
    },
    deleteButton: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: "#ffe5e5",
      justifyContent: "center",
      alignItems: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 4,
      marginRight: 10,
    },
    rightHeader: { flexDirection: "row", alignItems: "center", flex: 1 },
    searchInput: {
      height: 40,
      borderWidth: 1,
      borderColor: "#d6b48f",
      borderRadius: 8,
      paddingHorizontal: 10,
      backgroundColor: "#fff",
      color: "#333",
      flex: 1,
      marginRight: 8,
    },
    SearchBtn: {
      backgroundColor: "#d49a6a",
      width: 40,
      height: 40,
      borderRadius: 8,
      justifyContent: "center",
      alignItems: "center",
    },
    title: {
      fontSize: 26,
      fontWeight: "bold",
      color: "#6b4226",
      textAlign: "center",
      marginVertical: 10,
      textShadowColor: 'rgba(0, 0, 0, 0.15)',
      textShadowOffset: { width: 1, height: 2 },
      textShadowRadius: 3,
    },
    productCard: {
      backgroundColor: "#fff",
      padding: 10,
      borderRadius: 8,
      marginBottom: 15,
      alignItems: "center",
      width: "48%",
      elevation: 2,
    },
    selectedProduct: {
      borderColor: "green",
      borderWidth: 2,
    },
    productImage: { width: 120, height: 120, borderRadius: 8, marginBottom: 10 },
    productName: {
      fontSize: 14,
      fontWeight: "bold",
      color: "#6b4226",
      textAlign: "center",
    },
    row: { justifyContent: "space-between" },
    lowStockProduct: {
      borderColor: "#d9534f",
      borderWidth: 2,
    },
    lowStockIndicator: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#fff3f3",
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 4,
      marginTop: 4,
    },
    lowStockText: {
      color: "#d9534f",
      fontSize: 12,
      fontWeight: "600",
      marginLeft: 4,
    },
    searchContainer: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 10,
    },
    topActionsContainer: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 5,
    },
    selectionModeNote: {
      textAlign: "center",
      color: "#6b4226",
      fontSize: 14,
      fontWeight: "500",
      marginTop: 6,
      marginBottom: 10,
    },
    noResultsText: {
      textAlign: "center",
      color: "#999",
      fontSize: 16,
      marginTop: 20,
      fontStyle: "italic",
    },
  });

export default styles;