import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: "#f9f3ea",
      padding: 20,
    },
    title: {
      fontSize: 24,
      fontWeight: "bold",
      color: "#6b4226",
      textAlign: "center",
      marginBottom: 20,
    },
    searchWrapper: {
      flexDirection: "row",
      alignItems: "center",
      height: 44,
      borderColor: "#d2b48c",
      borderWidth: 1,
      borderRadius: 8,
      backgroundColor: "#fff",
      marginBottom: 20,
      paddingHorizontal: 10,
    },
    searchIcon: {
      marginRight: 8,
    },
    searchInput: {
      flex: 1,
      height: "100%",
      color: "#6b4226",
      fontSize: 16,
    },
    clearButton: {
      padding: 6,
    },
    userCard: {
      backgroundColor: "#fff",
      padding: 15,
      borderRadius: 10,
      marginBottom: 15,
      shadowColor: "#000",
      shadowOpacity: 0.1,
      shadowOffset: { width: 0, height: 2 },
      shadowRadius: 5,
      elevation: 2,
    },
    userInfo: {
      marginBottom: 10,
    },
    userName: {
      fontSize: 18,
      fontWeight: "bold",
      color: "#6b4226",
    },
    userEmail: {
      fontSize: 14,
      color: "#8a6f4d",
    },
    userRole: {
      fontSize: 14,
      color: "#a58c6f",
    },
    actionsRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    detailsButton: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#6b4226",
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 6,
    },
    detailsText: {
      color: "#fff",
      marginLeft: 6,
      fontWeight: "bold",
    },
    menuButton: {
      padding: 5,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.5)",
      justifyContent: "center",
      alignItems: "center",
      width: "100%",
    },
    modalContent: {
      backgroundColor: "#fff",
      padding: 20,
      borderRadius: 10,
      width: "80%",
      alignItems: "center",
    },
    modalButton: {
      width: "100%",
      padding: 12,
      borderRadius: 6,
      backgroundColor: "#d2b48c",
      marginVertical: 6,
      alignItems: "center",
    },
    modalButtonText: {
      color: "#fff",
      fontWeight: "bold",
    },
    deleteBtn: {
      backgroundColor: "#d9534f",
    },
    cancelBtn: {
      backgroundColor: "#6b4226",
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: "bold",
      color: "#6b4226",
      marginBottom: 10,
      textAlign: "center",
    },
  
    sendBtn: {
      backgroundColor: "#6b4226",
    },
    modalSubTitle: { fontSize: 16, color: "#6b4226", marginBottom: 10 },
    input: {
      width: "100%",
      height: 80,
      borderWidth: 1,
      borderColor: "#ccc",
      borderRadius: 8,
      padding: 10,
      marginBottom: 10,
      backgroundColor: "#f9f9f9",
      textAlignVertical: "top",
    },
    sendButton: {
      backgroundColor: "#6b4226",
      paddingVertical: 12,
      paddingHorizontal: 25,
      borderRadius: 8,
      alignItems: "center",
      width: "100%",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 3,
      elevation: 3,
    },
    sendButtonText: { color: "#fff", fontWeight: "bold", fontSize: 16 },
    closeButton: {
      backgroundColor: "#d9534f",
      paddingVertical: 10,
      paddingHorizontal: 25,
      borderRadius: 8,
      alignItems: "center",
      width: "100%",
      marginTop: 10,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 3,
      elevation: 3,
    },
    closeButtonText: { color: "#fff", fontWeight: "bold", fontSize: 16 },
    editModalContent: {
      backgroundColor: "#fff",
      borderRadius: 12,
      width: "90%",
      maxHeight: 420,
      overflow: "hidden",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.2,
      shadowRadius: 5,
      elevation: 5,
    },
    modalHeader: {
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      padding: 15,
      borderBottomWidth: 1,
      borderBottomColor: "#f0e6d6",
      position: "relative",
    },
    closeModalIcon: {
      position: "absolute",
      right: 15,
      padding: 5,
    },
    modalScrollView: {
      maxHeight: 280,
    },
    scrollContent: {
      padding: 20,
    },
    inputContainer: {
      width: "100%",
      marginBottom: 15,
    },
    inputLabel: {
      fontSize: 14,
      fontWeight: "600",
      color: "#6b4226",
      marginBottom: 5,
    },
    editInput: {
      borderWidth: 1,
      borderColor: "#d2b48c",
      borderRadius: 6,
      padding: 10,
      backgroundColor: "#faf6f0",
      color: "#6b4226",
    },
    roleSelector: {
      flexDirection: "row",
      justifyContent: "space-between",
    },
    roleButton: {
      flex: 1,
      padding: 10,
      borderWidth: 1,
      borderColor: "#d2b48c",
      borderRadius: 6,
      alignItems: "center",
      marginHorizontal: 5,
    },
    selectedRoleButton: {
      backgroundColor: "#6b4226",
      borderColor: "#6b4226",
    },
    roleButtonText: {
      color: "#6b4226",
      fontWeight: "500",
    },
    selectedRoleText: {
      color: "#fff",
    },
    editButtonsContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
      padding: 15,
      borderTopWidth: 1,
      borderTopColor: "#f0e6d6",
    },
    editActionButton: {
      flex: 1,
      padding: 12,
      borderRadius: 6,
      alignItems: "center",
      marginHorizontal: 5,
    },
    saveButton: {
      backgroundColor: "#6b4226",
    },
    cancelButton: {
      backgroundColor: "#d9534f",
    },
    actionButtonText: {
      color: "#fff",
      fontWeight: "bold",
    },
    noResultsContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      padding: 20,
    },
    noResultsText: {
      fontSize: 18,
      fontWeight: "bold",
      color: "#6b4226",
      marginTop: 15,
    },
    noResultsSubText: {
      fontSize: 14,
      color: "#a58c6f",
      textAlign: "center",
      marginTop: 8,
      maxWidth: "80%",
    },
    passwordContainer: {
      flexDirection: "row",
      alignItems: "center",
      borderWidth: 1,
      borderColor: "#d2b48c",
      borderRadius: 6,
      backgroundColor: "#faf6f0",
    },
    passwordInput: {
      flex: 1,
      padding: 10,
      color: "#6b4226",
    },
    eyeIcon: {
      padding: 10,
    },
  });

  
  export default styles;