import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: "#f9f3ea" },
    scrollContent: { padding: 16 },
    description: { fontSize: 16, color: "#6b4226", marginTop: 16, textAlign: "justify" },
    price: { fontSize: 18, fontWeight: "bold", color: "#6b4226", textAlign: "center" },
    deleteButton: {
        backgroundColor: "#d9534f",
        padding: 10,
        borderRadius: 8,
        alignItems: "center",
        marginTop: 10,
    },
    deleteButtonText: {
        color: "#fff",
        fontSize: 16,
        fontWeight: "bold",
    },
    title: { fontSize: 24, fontWeight: "bold", color: "#6b4226", textAlign: "center", padding: 10, marginBottom: 5 },
    image: { width: "100%", height: 450, borderRadius: 10 },
    input: { borderWidth: 1, borderColor: "#6b4226", padding: 8, borderRadius: 5, marginVertical: 8 },
    uploadButton: { backgroundColor: "#6b4226", padding: 10, borderRadius: 8, alignItems: "center", marginVertical: 10 },
    uploadButtonText: { color: "#fff", fontSize: 16, fontWeight: "bold" },
    editButton: { backgroundColor: "#6b4226", padding: 10, borderRadius: 8, alignItems: "center", marginTop: 10 },
    editButtonText: { color: "#fff", fontSize: 16, fontWeight: "bold" },
    saveButton: { backgroundColor: "#4caf50", padding: 10, borderRadius: 8, alignItems: "center", marginTop: 10 },
    saveButtonText: { color: "#fff", fontSize: 16, fontWeight: "bold" },
    error: { fontSize: 18, color: "red", textAlign: "center", marginTop: 20 },
    editContainer: {
        backgroundColor: '#f5e9d9',
        borderRadius: 20,
        padding: 20,
        marginBottom: 20,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
        borderWidth: 1,
        borderColor: '#e8d5c4',
    },
    editLabel: {
        fontSize: 16,
        fontWeight: '600',
        color: '#6b4226',
        marginBottom: 8,
        marginTop: 15,
    },
    editInput: {
        borderWidth: 1,
        borderColor: '#e8d5c4',
        borderRadius: 12,
        padding: 12,
        fontSize: 16,
        backgroundColor: '#fff',
        marginBottom: 5,
    },
    editDescriptionInput: {
        height: 100,
        textAlignVertical: 'top',
        borderWidth: 1,
        borderColor: '#e8d5c4',
        borderRadius: 12,
        padding: 12,
        fontSize: 16,
        backgroundColor: '#fff',
        marginBottom: 5,
    },
    editImageContainer: {
        alignItems: 'center',
        marginVertical: 15,
    },
    editImage: {
        width: '100%',
        height: 200,
        borderRadius: 12,
        marginBottom: 10,
    },
    editButtonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 20,
    },
    editSaveButton: {
        flex: 1,
        backgroundColor: '#4caf50',
        padding: 15,
        borderRadius: 12,
        alignItems: 'center',
        marginRight: 10,
    },
    editCancelButton: {
        flex: 1,
        backgroundColor: '#6b4226',
        padding: 15,
        borderRadius: 12,
        alignItems: 'center',
        marginLeft: 10,
    },
    viewContainer: {
        backgroundColor: '#fff',
        borderRadius: 20,
        padding: 0,
        marginBottom: 20,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
        overflow: 'hidden',
    },
    productImage: {
        width: '100%',
        height: 300,
        borderBottomLeftRadius: 20,
        borderBottomRightRadius: 20,
    },
    contentContainer: {
        padding: 20,
    },
    productTitle: {
        fontSize: 28,
        fontWeight: 'bold',
        color: '#6b4226',
        marginBottom: 15,
        textTransform: 'capitalize',
    },
    priceTag: {
        backgroundColor: '#6b4226',
        paddingHorizontal: 15,
        paddingVertical: 8,
        borderRadius: 20,
        alignSelf: 'flex-start',
        marginBottom: 20,
    },
    priceText: {
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#6b4226',
        marginBottom: 10,
        marginTop: 15,
    },
    descriptionText: {
        fontSize: 16,
        color: '#666',
        lineHeight: 24,
        marginBottom: 20,
    },
    buttonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 20,
        paddingTop: 20,
        borderTopWidth: 1,
        borderTopColor: '#f0f0f0',
    },
    profitContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 20,
        backgroundColor: '#f9f3ea',
        borderRadius: 12,
        padding: 15,
        flexWrap: 'wrap',
    },
    profitItem: {
        alignItems: 'center',
        minWidth: '30%',
    },
    profitLabel: {
        fontSize: 14,
        color: '#666',
        marginBottom: 5,
    },
    profitValue: {
        fontSize: 16,
        fontWeight: '600',
        color: '#6b4226',
    },
    buttonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
});


export default styles;