import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: "#f9f3ea", padding: 16 },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 20,
    },
    clearButton: {
      padding: 5,
      marginRight: 5,
    },
    headerTitle: {
      fontSize: 24,
      fontWeight: "bold",
      color: "#6b4226",
      textAlign: "center",
      textShadowColor: "rgba(0, 0, 0, 0.15)",
      textShadowOffset: { width: 1, height: 2 },
      textShadowRadius: 3,
    },
    cartItem: {
      flexDirection: "row",
      backgroundColor: "#fff",
      borderRadius: 12,
      padding: 10,
      marginBottom: 10,
      alignItems: "center",
      elevation: 3,
    },
    itemImage: { width: 80, height: 80, borderRadius: 8, marginRight: 10 },
    modalImage: { width: 200, height: 200, borderRadius: 8, marginBottom: 15 },
    placeholderImage: {
      backgroundColor: "#F8F1E7",
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: "#E5D3C2",
    },
    placeholderText: {
      color: "#7B6D63",
      fontSize: 14,
      textAlign: "center",
      padding: 5,
    },
    errorText: {
      color: "#ff4444",
      fontSize: 14,
      marginBottom: 10,
      textAlign: "center",
    },
    itemDetails: { flex: 1 },
    itemName: { fontSize: 16, fontWeight: "bold", color: "#6b4226" },
    itemPrice: { fontSize: 14, color: "#6b4226" },
    quantityContainer: {
      flexDirection: "row",
      alignItems: "center",
      marginTop: 5,
    },
    quantityText: { fontSize: 16, marginHorizontal: 10 },
    removeButton: { backgroundColor: "#ff4444", padding: 8, borderRadius: 30 },
    loading: { marginTop: 20 },
    emptyMessage: {
      fontSize: 18,
      color: "#6b4226",
      textAlign: "center",
      marginTop: 20,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0, 0, 0, 0.5)",
      justifyContent: "center",
      alignItems: "center",
    },
    modalContent: {
      backgroundColor: "#fff",
      width: "85%",
      padding: 20,
      borderRadius: 15,
      alignItems: "center",
      elevation: 5,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: "bold",
      color: "#6b4226",
      marginBottom: 10,
    },
    modalDescription: {
      fontSize: 16,
      color: "#555",
      textAlign: "center",
      marginBottom: 10,
    },
    modalPrice: {
      fontSize: 18,
      fontWeight: "bold",
      color: "#d49a6a",
      marginBottom: 15,
    },
    closeButton: {
      backgroundColor: "#6b4226",
      padding: 12,
      borderRadius: 8,
      width: "45%",
      alignItems: "center",
    },
    closeButtonText: { color: "#fff", fontSize: 16, fontWeight: "bold" },
    checkoutContainer: { position: "absolute", bottom: 80, left: 20, right: 20 },
    totalText: {
      fontSize: 18,
      fontWeight: "bold",
      color: "#6b4226",
      textAlign: "center",
    },
    checkoutButton: { backgroundColor: "#6b4226", padding: 15, borderRadius: 10 },
    checkoutButtonText: {
      color: "#fff",
      fontSize: 18,
      fontWeight: "bold",
      textAlign: "center",
    },
    itemQuantity: { fontSize: 14, color: "#6b4226", marginTop: 5 },
    unavailableProductContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      padding: 20,
    },
    modalButtonsContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginTop: 20,
      width: "100%",
    },
    removeButtonText: {
      color: "#fff",
      fontSize: 16,
      fontWeight: "bold",
      marginLeft: 10,
    },
    modalRemoveButton: {
      backgroundColor: "#ff4444",
      padding: 12,
      borderRadius: 8,
      width: "45%",
      alignItems: "center",
      marginRight: 10,
    },
    cartItemContent: { flexDirection: "row", alignItems: "center", flex: 1 },
    tapToRemove: {
      color: "#6b4226",
      fontSize: 14,
      textAlign: "center",
      marginTop: 5,
    },
  });

  export default styles;