import { StyleSheet } from 'react-native';
import { Platform } from 'react-native';
const styles = StyleSheet.create({
  modalCard: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 25,
    width: "85%",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalHeaderText: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#6b4226",
    marginBottom: 25,
  },
  shippingMethodButton: {
    borderColor: "#6b4226",
    borderWidth: 1.5,
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 20,
    width: "100%",
    marginBottom: 15,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  shippingMethodText: {
    fontWeight: "600",
    fontSize: 16,
  },
  shippingMethodIcon: {
    marginRight: 10,
  },
  modalCloseButton: {
    backgroundColor: "#D9534F",
    paddingVertical: 12,
    paddingHorizontal: 25,
    borderRadius: 8,
    alignItems: "center",
    marginTop: 20,
    width: "100%",
  },
  modalCloseText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
  },
    container: {
      flex: 1,
      backgroundColor: "#FAF5EF",
      padding: 16,
    },
    title: {
      fontSize: 26,
      fontWeight: "bold",
      color: "#5A3827",
      textAlign: "center",
      marginBottom: 10,
    },
    scrollView: {
      flex: 1,
      padding: 16,
    },
    modalContainer: {
      backgroundColor: "#fff",
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      padding: 24,
      position: "absolute",
      bottom: 0,
      left: 0,
      right: 0,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: -2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 10,
    },
    sectionContainer: {
      borderWidth: 1.5,
      borderColor: "#E5D3C2",
      borderRadius: 12,
      overflow: "hidden",
      backgroundColor: "#FFF",
      padding: 16,
      marginTop: 16,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      elevation: 3,
    },
    sectionTitle: {
      fontSize: 16,
      fontWeight: "bold",
      color: "#5A3827",
      marginBottom: 10,
    },
    cartItem: {
      flexDirection: "row",
      backgroundColor: "#FFFFFF",
      borderRadius: 16,
      padding: 16,
      marginBottom: 12,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.15,
      shadowRadius: 10,
      elevation: 5,
      borderWidth: 1,
      borderColor: "#E5D3C2",
    },
    itemImage: {
      width: 100,
      height: 100,
      borderRadius: 12,
      marginRight: 16,
      borderWidth: 1,
      borderColor: "#E5D3C2",
    },
    itemDetails: {
      flex: 1,
      justifyContent: "space-between",
      paddingVertical: 4,
    },
    itemName: {
      fontSize: 20,
      fontWeight: "bold",
      color: "#5A3827",
      marginBottom: 8,
    },
    itemPrice: {
      fontSize: 18,
      color: "#5A3827",
      fontWeight: "600",
      marginBottom: 6,
    },
    itemQuantity: {
      fontSize: 16,
      color: "#7B6D63",
      backgroundColor: "#F8F1E7",
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 8,
      alignSelf: "flex-start",
      borderWidth: 1,
      borderColor: "#E5D3C2",
    },
    deliveryDetailsBox: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      backgroundColor: "#F8F1E7",
      padding: 12,
      borderRadius: 10,
      borderWidth: 1.5,
      borderColor: "#E5D3C2",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      elevation: 3,
    },
    deliveryName: { fontSize: 16, color: "#5A3827", fontWeight: "bold" },
    deliveryAddress: { fontSize: 14, color: "#7B6D63", lineHeight: 20 },
    shippingOption: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      backgroundColor: "#FAEDE1",
      padding: 12,
      borderRadius: 10,
    },
    shippingText: { fontSize: 14, color: "#5A3827", fontWeight: "bold" },
    promoContainer: {
      flexDirection: "row",
      alignItems: "center",
      borderWidth: 1.5,
      borderColor: "#E5D3C2",
      borderRadius: 12,
      overflow: "hidden",
      backgroundColor: "#FFF",
      padding: 9,
      marginTop: 15,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      elevation: 3,
    },
    promoInput: {
      flex: 1,
      padding: 12,
      fontSize: 14,
      color: "#5A3827",
    },
    applyButton: {
      backgroundColor: "#5A3827",
      paddingHorizontal: 15,
      paddingVertical: 10,
      borderTopRightRadius: 10,
      borderBottomRightRadius: 10,
    },
    applyButtonText: {
      color: "#fff",
      fontSize: 14,
      fontWeight: "bold",
    },
    paymentContainer: {
      marginTop: 20,
      padding: 16,
      backgroundColor: "#fff",
      borderRadius: 12,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      elevation: 3,
    },
    paymentTitle: {
      fontSize: 18,
      fontWeight: "bold",
      color: "#5A3827",
      marginBottom: 10,
    },
    paymentOptionsContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 10,
    },
    paymentOptionButton: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 12,
      paddingHorizontal: 15,
      borderRadius: 8,
      backgroundColor: '#FAEDE1',
      borderWidth: 1.5,
      borderColor: '#E5D3C2',
      gap: 8,
    },
    paymentText: {
      fontSize: 14,
      color: "#5A3827",
      letterSpacing: 0.5,
      fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    },
    selectedOptionText: {
      color: '#fff',
    },
    selectedOption: {
      backgroundColor: "#5A3827",
      borderColor: "#5A3827",
    },
    checkoutContainer: { marginTop: 20, alignItems: "center" },
    totalText: { fontSize: 20, fontWeight: "bold", color: "#5A3827" },
    checkoutButton: {
      backgroundColor: "#5A3827",
      padding: 15,
      borderRadius: 12,
      marginTop: 10,
      width: "100%",
    },
    checkoutButtonText: {
      color: "#fff",
      fontSize: 18,
      fontWeight: "bold",
      textAlign: "center",
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.5)",
      justifyContent: "center",
      alignItems: "center",
    },
    modalContent: {
      backgroundColor: "#FFF",
      padding: 24,
      borderRadius: 20,
      width: "90%",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 10,
      elevation: 10,
      alignItems: "center",
    },
    modalTitle: {
      fontSize: 22,
      fontWeight: "bold",
      color: "#5A3827",
      marginBottom: 20,
      textAlign: "center",
    },
    modalText: {
      fontSize: 16,
      color: "#5A3827",
      fontWeight: "bold",
      marginBottom: 0,
    },
    modalCloseButtonRed: {
      backgroundColor: "#D9534F",
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 8,
      alignItems: "center",
      marginTop: 15,
    },
    modalCloseButtonText: {
      color: "#fff",
      fontSize: 16,
      fontWeight: "bold",
    },
    modalButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 12,
      paddingHorizontal: 15,
      borderRadius: 8,
      backgroundColor: "#FAEDE1",
      marginVertical: 5,
      width: "100%",
      borderWidth: 1.5,
      borderColor: "#E5D3C2",
      gap: 10,
    },
    addressItem: {
      width: "100%",
      backgroundColor: "#FAF5EF",
      padding: 16,
      marginVertical: 8,
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: "#E5D3C2",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 5,
      elevation: 3,
    },
    selectedAddress: {
      borderColor: "#5A3827",
      borderWidth: 2,
      backgroundColor: "#F8F1E7",
    },
    loading: { marginTop: 20 },
    emptyMessage: {
      fontSize: 18,
      color: "#6b4226",
      textAlign: "center",
      marginTop: 20,
    },
    noAddressContainer: {
      alignItems: "center",
      padding: 20,
    },
    noAddressText: {
      fontSize: 16,
      color: "#6b4226",
      marginBottom: 10,
    },
    addAddressButton: {
      backgroundColor: "#6b4226",
      paddingVertical: 12,
      paddingHorizontal: 25,
      borderRadius: 8,
      alignItems: "center",
    },
    addAddressText: {
      color: "#fff",
      fontSize: 16,
      fontWeight: "bold",
    },
    input: {
      width: "100%",
      height: 45,
      borderWidth: 1,
      borderColor: "#ccc",
      borderRadius: 8,
      padding: 10,
      marginBottom: 10,
      backgroundColor: "#fff",
    },
    addButton: {
      backgroundColor: "#6b4226",
      paddingVertical: 12,
      paddingHorizontal: 25,
      borderRadius: 8,
      alignItems: "center",
      width: "100%",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 3,
      elevation: 3,
    },
    addButtonText: {
      color: "#fff",
      fontSize: 16,
      fontWeight: "bold",
    },
    deliveryDateBox: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      backgroundColor: "#F8F1E7",
      padding: 12,
      borderRadius: 10,
      borderWidth: 1.5,
      borderColor: "#E5D3C2",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      elevation: 3,
    },
    deliveryDateText: {
      fontSize: 16,
      color: "#5A3827",
      fontWeight: "bold",
    },
    summaryContainer: {
      marginTop: 20,
      padding: 16,
      backgroundColor: "#fff",
      borderRadius: 12,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      elevation: 3,
    },
    summaryTitle: {
      fontSize: 18,
      fontWeight: "bold",
      color: "#5A3827",
      marginBottom: 15,
    },
    summaryRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingVertical: 8,
      borderBottomWidth: 1,
      borderBottomColor: "#E5D3C2",
    },
    summaryLabel: {
      fontSize: 16,
      color: "#7B6D63",
    },
    summaryValue: {
      fontSize: 16,
      color: "#5A3827",
      fontWeight: "500",
    },
    discountValue: {
      color: "#28a745",
    },
    totalRow: {
      borderBottomWidth: 0,
      marginTop: 10,
      paddingTop: 10,
      borderTopWidth: 2,
      borderTopColor: "#E5D3C2",
    },
    totalLabel: {
      fontSize: 18,
      fontWeight: "bold",
      color: "#5A3827",
    },
    totalValue: {
      fontSize: 18,
      fontWeight: "bold",
      color: "#5A3827",
    },
  });
  export default styles;