import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  quickAddButton: {
    width: 150,
    height: 45,
    borderRadius: 22,
    backgroundColor: "#D49A6A",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#B87D50",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  quickAddButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.4)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: "#fff",
    padding: 20,
    borderRadius: 10,
    width: "80%",
    alignItems: "center",
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 10,
    textAlign: "center",
  },
  quantityContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  qtyBtn: {
    fontSize: 24,
    padding: 10,
  },
  qtyText: {
    fontSize: 18,
  },
  addToCartButton: {
    position: "absolute",
    bottom: 16,
    right: 16,
    backgroundColor: "#D49A6A",
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
    elevation: 3,
    zIndex: 5,
    justifyContent: "center",
    alignItems: "center",
  },
  quantityModal: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 999,
  },
  quantityModalContent: {
    backgroundColor: "#fff",
    padding: 20,
    borderRadius: 10,
    width: "80%",
    alignItems: "center",
  },
  quantityTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 10,
  },
  confirmAddButton: {
    backgroundColor: "#6b4226",
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
    marginTop: 20,
  },
  qtyControl: {
    backgroundColor: "#e1d5c9",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 4,
  },
  qtyControlText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#6b4226",
  },
  addToCartButtonText: {
    color: "#fff",
    textAlign: "center",
    fontWeight: "bold",
  },
  container: {
    flex: 1,
    padding: 15,
    backgroundColor: "#f9f3ea",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  leftHeader: {
    flex: 1,
    alignItems: "flex-start",
  },
  centerHeader: {
    flex: 1,
    alignItems: "center",
  },

  profileContainer: { flexDirection: "row", alignItems: "center" },
  profileImage: { width: 40, height: 40, borderRadius: 20, marginRight: 10 },
  userName: { fontSize: 16, fontWeight: "bold", color: "#6b4226" },
  rightHeader: { flexDirection: "row", alignItems: "center" },
  searchInput: {
    height: 40,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 10,
    backgroundColor: "#fff",
  },
  SearchBtn: {
    backgroundColor: "#ffcc99",
    padding: 10,
    borderRadius: 8,
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
  },
  title: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#6b4226",
    textAlign: "center",
  },
  favoritesButton: {
    backgroundColor: "#6b4226",
    paddingVertical: 8,
    borderRadius: 8,
    marginVertical: 8,
    alignItems: "center",
  },
  favoritesButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  favoriteButton: { position: "absolute", bottom: 8, right: 8 },
  hotCakeList: { paddingHorizontal: 8 },
  horizontalScrollContainer: { marginBottom: 8 },
  horizontalProductCard: {
    flexDirection: "row",
    backgroundColor: "#fff",
    padding: 10,
    borderRadius: 12,
    marginBottom: 16,
    elevation: 2,
    alignItems: "center",
    position: "relative",
  },
  productImage: {
    width: "100%",
    height: 200,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
  },
  productName: {
    fontSize: 17,
    fontWeight: "bold",
    color: "#6b4226",
    textAlign: "center",
    marginBottom: 6,
    flexWrap: "wrap",
    maxWidth: "100%",
  },
  row: { justifyContent: "space-between" },
  itemPrice: {},
  outOfStockText: { fontSize: 14, color: "#d9534f", fontWeight: "bold" },

  verticalCardContainer: {
    width: "48%",
    height: 320,
    marginBottom: 16,
    position: "relative",
  },
  verticalCardTouchable: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 10,
    alignItems: "center",
    elevation: 3,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    height: "100%",
    justifyContent: "space-between",
  },
  favoriteButtonTop: {
    position: "absolute",
    top: 10,
    right: 10,
    backgroundColor: "#fff",
    borderRadius: 15,
    width: 30,
    height: 30,
    justifyContent: "center",
    alignItems: "center",
    elevation: 2,
    zIndex: 1,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  productInfo: {
    alignItems: "center",
    paddingHorizontal: 8,
    paddingBottom: 28,
    minHeight: 100,
    marginTop: 0,
  },

  priceText: {
    fontSize: 18,
    fontWeight: "700",
    color: "#d49a6a",

    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    overflow: "hidden",
    marginBottom: 4,
  },
  outOfStockLabel: {
    fontSize: 13,
    color: "#fff",
    backgroundColor: "#d9534f",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
    marginTop: 4,
  },
  lowStockLabel: {
    fontSize: 11,
    color: "#ff9900",
    backgroundColor: "#fff0e6",
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 4,
    marginTop: 2,
    fontWeight: "bold",
    alignSelf: "flex-start",
    marginBottom: 4,
  },
  favoriteLabel: {
    marginTop: 6,
    fontSize: 12,
    color: "#d9534f",
    fontWeight: "bold",
  },
  filtersContainer: {
    flexDirection: "row",
    marginVertical: 10,
  },
  filterChip: {
    backgroundColor: "#fffaf2",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    marginRight: 10,
    borderWidth: 1,
    borderColor: "#d49a6a",
    elevation: 2,
  },
  filterText: {
    color: "#6b4226",
    fontWeight: "bold",
  },
  activeFilterChip: {
    backgroundColor: "#d49a6a",
    borderColor: "#6b4226",
  },
  activeFilterText: {
    color: "#fff",
  },
  wideProductImage: {
    width: 200,
    height: 140, // גובה מוגדל/מותאם
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    marginRight: 16,
  },
  wideProductInfo: {
    flex: 1,
    height: 150,
    justifyContent: "space-between",
    paddingVertical: 8,
    paddingRight: 40,
  },
  priceTextRight: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#6b4226",
    textAlign: "right",
    marginTop: "auto",
  },
  searchBlock: {
    backgroundColor: "#f9f3ea",
    borderRadius: 10,
    padding: 10,
    marginVertical: 10,
    elevation: 2,
  },
  searchInputFull: {
    height: 40,
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 8,
    paddingHorizontal: 10,
    backgroundColor: "#fff",
    textAlign: "left",
  },
  banner: {
    backgroundColor: "#fff3e6",
    padding: 20,
    borderRadius: 10,
    marginBottom: 10,
    alignItems: "center",
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    marginVertical: 10,
    color: "#6b4226",
  },
  graphContainer: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    elevation: 3,
  },
  closeModalButton: {
    position: "absolute",
    top: 10,
    right: 10,
  },
});

export default styles;