import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: "#f9f3ea",
    },
    scrollView: {
      flex: 1,
    },
    scrollContent: {
      flexGrow: 1,
    },
    container: {
      flex: 1,
      alignItems: "center",
      backgroundColor: "#f9f3ea",
      paddingVertical: 40,
      paddingHorizontal: 20,
    },
    loadingContainer: {
      justifyContent: "center",
    },
    profileImagePlaceholder: {
      width: 150,
      height: 150,
      borderRadius: 80,
      backgroundColor: "#e0e0e0",
      marginBottom: 40,
    },
    userNamePlaceholder: {
      width: 150,
      height: 24,
      backgroundColor: "#e0e0e0",
      borderRadius: 4,
      marginBottom: 10,
    },
    titlePlaceholder: {
      width: 80,
      height: 18,
      backgroundColor: "#e0e0e0",
      borderRadius: 4,
      marginBottom: 20,
    },
    loader: {
      marginVertical: 20,
      transform: [{ scale: 1.2 }],
    },
    loadingText: {
      fontSize: 16,
      color: "#6b4226",
      marginTop: 10,
    },
    profileImage: {
      width: 150,
      height: 150,
      borderRadius: 80,
      marginBottom: 20,
      borderWidth: 2,
      borderColor: "#d49a6a",
    },
    userName: {
      fontSize: 22,
      fontWeight: "bold",
      color: "#6b4226",
    },
    lastLoginText: {
      fontSize: 14,
      color: "#8d6e63",
      marginTop: 4,
      marginBottom: 12,
    },
    title: {
      fontSize: 18,
      color: "#6b4226",
      marginBottom: 20,
    },
    button: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#d49a6a",
      padding: 15,
      borderRadius: 30,
      width: "80%",
      justifyContent: "center",
      marginBottom: 10,
      marginTop: 6,
    },
    logoutButton: {
      backgroundColor: "#e63946",
      marginTop: 6,
    },
    buttonText: {
      color: "#fff",
      fontSize: 16,
      fontWeight: "bold",
      marginLeft: 10,
    },
    contactLabel: {
      fontSize: 16,
      fontWeight: "bold",
      marginTop: 30,
      marginBottom: 10,
      textAlign: "center",
      color: "#6b4226",
    },
    contactButtonsContainer: {
      flexDirection: "row",
      justifyContent: "center",
      gap: 10,
      marginBottom: 8,
    },
    contactButtonsWrapper: {
      marginTop: 30,
      marginBottom: 10,
      alignItems: "center",
    },
    iconButton: {
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "#d49a6a",
      padding: 6,
      borderRadius: 20,
      width: 36,
      height: 36,
    },
  


  contactInputSection: {
    width: "90%",
    marginTop: 15,
    alignItems: "center",
  },
  contactInputLabel: {
    alignSelf: "flex-start",
    marginBottom: 5,
    fontSize: 14,
    color: "#5a3827",
    fontWeight: "600",
  },
  contactInput: {
    width: "100%",
    height: 100,
    backgroundColor: "#fff",
    borderColor: "#ccc",
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
    textAlignVertical: "top",
    color: "#333",
  },
  sendButton: {
    backgroundColor: "#d49a6a",
    marginTop: 10,
    paddingVertical: 10,
    paddingHorizontal: 30,
    borderRadius: 25,
  },
  sendButtonText: {
    color: "#fff",
    fontWeight: "600",
    fontSize: 16,
  },
  headerTitle: {
    fontSize: 30,
    fontWeight: "bold",
    color: "#6b4226",
    marginBottom: 20,
    textAlign: "center",
  },
  statCard: {
    backgroundColor: "#fff",
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 8,
    alignItems: "center",
    marginTop: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 1,
    width: "50%",
    borderWidth: 1,
    borderColor: "#eee",
  },
  statLabel: {
    fontSize: 12,
    color: "#6b4226",
    fontWeight: "500",
    marginBottom: 2,
  },
  statValue: {
    fontSize: 13,
    fontWeight: "600",
    color: "#d49a6a",
  },
  levelCard: {
    width: "80%",
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 16,
    marginVertical: 20,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  levelTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#6b4226",
    marginBottom: 10,
  },
  levelBar: {
    width: "100%",
    height: 10,
    backgroundColor: "#eee",
    borderRadius: 5,
    overflow: "hidden",
  },
  levelProgress: {
    width: "60%",
    height: "100%",
    backgroundColor: "#d49a6a",
  },
  levelText: {
    marginTop: 8,
    fontSize: 14,
    fontWeight: "600",
    color: "#6b4226",
  },
  contactHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 20,
    marginBottom: 6,
  },
  contactModal: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: [{ translateX: -150 }, { translateY: -150 }],
    width: 320,
    backgroundColor: "#fff",
    padding: 28,
    borderRadius: 20,
    elevation: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    alignItems: "center",
    zIndex: 999,
  },
  contactModalCloseButton: {
    position: "absolute",
    top: 8,
    right: 8,
    zIndex: 1,
  },
});
  export default styles;