import { Dimensions, StyleSheet } from 'react-native';
const { width } = Dimensions.get("window");
const cardWidth = (width - 48) / 2;


const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#f9f3ea",
    },
    header: {
        borderBottomWidth: 1,
        borderBottomColor: "#e8d7c3",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.08,
        shadowRadius: 2,
        elevation: 2,
        paddingTop: 8,
    },
    headerContent: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingHorizontal: 20,
        paddingBottom: 12,
    },
    title: {
        fontSize: 28,
        fontWeight: "800",
        color: "#6b4226",
        letterSpacing: 0.5,
        textShadowColor: 'rgba(0, 0, 0, 0.1)',
        textShadowOffset: { width: 1, height: 1 },
        textShadowRadius: 2,
    },
    rightHeader: {
        flexDirection: "row",
        alignItems: "center",
        width: 200,
        justifyContent: "flex-end",
    },
    searchContainer: {
        width: 150,
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#f9f3ea",
        borderRadius: 20,
        borderWidth: 1,
        borderColor: "#e0e0e0",
        height: 36,
        marginRight: 8,
        paddingLeft: 8,
    },
    searchIcon: {
        marginRight: 4,
    },
    searchInput: {
        flex: 1,
        height: 36,
        color: "#6b4226",
        fontSize: 14,
        letterSpacing: 0.3,
        paddingRight: 10,
    },
    clearSearchButton: {
        width: 30,
        height: 36,
        justifyContent: "center",
        alignItems: "center",
    },
    searchButton: {
        width: 36,
        height: 36,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#f9f3ea",
        borderRadius: 18,
        marginRight: 7
    },
    scrollView: {
        flex: 1,
        padding: 10,
    },
    recipeGrid: {
        padding: 2,
        paddingBottom: 50,
    },
    recipeCard: {
        width: cardWidth,
        backgroundColor: "#fff",
        borderRadius: 12,
        marginVertical: 6,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
        overflow: "hidden",
    },
    recipeImage: {
        width: "100%",
        height: 120,
        borderTopLeftRadius: 15,
        borderTopRightRadius: 15,
    },
    recipeInfo: {
        padding: 10,
        paddingBottom: 8,
    },
    recipeTitle: {
        fontSize: 15,
        fontWeight: "700",
        color: "#6b4226",
        marginBottom: 4,
        letterSpacing: 0.3,
        height: 34,
    },
    recipeDescription: {
        fontSize: 13,
        color: "#666",
        marginBottom: 6,
        lineHeight: 18,
        letterSpacing: 0.2,
        height: 36,
    },
    metaRow: {
        flexDirection: "row",
        alignItems: "center",
        marginTop: 2,
        marginBottom: 4,
    },
    metaItem: {
        flexDirection: "row",
        alignItems: "center",
        marginRight: 8,
    },
    metaText: {
        fontSize: 11,
        color: "#6b4226",
        marginLeft: 2,
        fontWeight: "500",
    },
    modalOverlay: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: "rgba(0, 0, 0, 0.5)",
        justifyContent: "center",
        alignItems: "center",
    },
    modalContent: {
        width: "90%",
        backgroundColor: "#fff",
        borderRadius: 20,
        maxHeight: "90%",
    },
    modalImage: {
        width: "100%",
        height: 250,
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
    },
    modalTextContent: {
        padding: 20,
    },
    closeButton: {
        position: "absolute",
        top: 10,
        right: 10,
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: "rgba(255, 255, 255, 0.9)",
        justifyContent: "center",
        alignItems: "center",
        zIndex: 1,
    },
    modalTitle: {
        fontSize: 26,
        fontWeight: '800',
        color: '#6b4226',
        letterSpacing: 0.5,
        flex: 1,
        flexWrap: 'wrap',
        paddingRight: 60,
    },
    modalDescription: {
        fontSize: 16,
        color: "#666",
        marginBottom: 20,
        textAlign: "center",
        lineHeight: 24,
        letterSpacing: 0.3,
    },
    modalMeta: {
        flexDirection: "row",
        justifyContent: "space-around",
        marginBottom: 20,
        paddingHorizontal: 20,
    },
    metaBackground: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#f9f3ea",
        paddingHorizontal: 15,
        paddingVertical: 8,
        borderRadius: 20,
        marginHorizontal: 5,
    },
    modalMetaText: {
        fontSize: 16,
        color: "#6b4226",
        marginLeft: 8,
        fontWeight: "600",
        letterSpacing: 0.3,
    },
    section: {
        marginTop: 20,
        marginBottom: 10,
    },
    sectionTitle: {
        fontSize: 20,
        fontWeight: "700",
        color: "#6b4226",
        marginBottom: 12,
        letterSpacing: 0.3,
    },
    ingredient: {
        fontSize: 15,
        color: "#666",
        marginBottom: 8,
        lineHeight: 22,
        letterSpacing: 0.2,
    },
    instruction: {
        fontSize: 15,
        color: "#666",
        marginBottom: 12,
        lineHeight: 22,
        letterSpacing: 0.2,
    },
    likeButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(255, 240, 245, 0.6)',
        paddingHorizontal: 5,
        paddingVertical: 2,
        borderRadius: 8,
        alignSelf: 'flex-start',
    },
    likeCount: {
        marginLeft: 3,
        fontSize: 11,
        fontWeight: '500',
        color: '#6b4226',
    },
    modalTitleRow: {
        position: 'relative',        // מאפשר לכפתור להתמקם יחסית לשורה
        marginBottom: 10,
    },
    modalLikeButton: {
        position: 'absolute',        // כפתור יושב בפינה – לא מושפע מאורך הכותרת
        top: 0,
        right: 0,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(255,255,255,0.8)',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 20,
    },
    modalLikeCount: {
        marginLeft: 6,
        fontSize: 16,
        fontWeight: 'bold',
        color: '#6b4226',
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    loadingText: {
        marginTop: 10,
        fontSize: 16,
        color: '#6b4226',
    },
    errorContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    errorText: {
        marginTop: 10,
        fontSize: 16,
        color: '#ff4d6d',
        textAlign: 'center',
        marginBottom: 20,
    },
    retryButton: {
        backgroundColor: '#6b4226',
        paddingHorizontal: 20,
        paddingVertical: 10,
        borderRadius: 8,
    },
    retryButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
        height: 300,
    },
    emptyText: {
        marginTop: 10,
        fontSize: 16,
        color: '#6b4226',
        textAlign: 'center',
    },
    columnWrapper: {
        justifyContent: 'space-between',
        marginHorizontal: 16,
    },
    newBadge: {
        position: 'absolute',
        top: 8,
        right: 8,
        backgroundColor: '#ff4d6d',
        paddingHorizontal: 6,
        paddingVertical: 3,
        borderRadius: 6,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 2,
        elevation: 3,
    },
    newBadgeText: {
        fontSize: 10,
        fontWeight: 'bold',
        color: '#fff',
    },
    modalImageContainer: {
        position: 'relative',
    },
    modalNewBadge: {
        position: 'absolute',
        top: 16,
        left: 16,
        backgroundColor: '#ff4d6d',
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderRadius: 8,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 2,
        elevation: 3,
    },
    modalNewBadgeText: {
        fontSize: 12,
        fontWeight: 'bold',
        color: '#fff',
        letterSpacing: 0.3,
    },
}); 

export default styles;